/**
 * 화면 인벤토리 — 실제 앱 사이드바(AppSidebar.tsx) 그룹·순서를 따릅니다.
 * group: 사이드바 카테고리. 번호는 그룹 순서대로 01부터 붙입니다.
 */
export const screens = [
  // ── 검색 ──────────────────────────────────────────────
  {
    no: '01', key: 'search-chat', group: '검색', name: '지원사업 검색', route: '/app/chat · /', owner: '김건우',
    prio: 'P0', prioWhy: '발표 시연의 첫 화면 — 하이브리드 검색이 개발 Docker에 올라가야 시연 결과가 지금 코드와 같아집니다',
    tagline: '기업 상황을 한 줄로 쓰면 공식 공고를 찾아 주는 진입 화면', status: '구현 완료', tone: 'live',
    demo: true, notes: [],
    lastChanged: '2026-09-13',
    biz: '이 서비스가 파는 것은 "검색"이 아니라 담당자의 판단 시간입니다. 공고를 하나씩 열어 우리 회사가 대상인지 확인하던 일을 한 줄 입력으로 줄이는 것이 이 화면의 전부이고, 나머지 화면은 여기서 나온 결과를 검증·관리·신청으로 잇는 뒤따르는 단계입니다. 첫 화면에는 입력 하나만 남기고 조건은 대화로 좁힙니다.',
    value: ['첫 방문자가 예시 문장을 고르지 않고 자기 문장을 쓴다', '검색 1회당 상세로 넘어가는 카드가 1건 이상', '조건 확인 카드를 취소하지 않고 그대로 검색'],
    elements: [
      { name: 'AI 대화 검색 입력', state: '구현', tone: 'live' },
      { name: '조건 확인 카드(확인 후 검색)', state: '구현', tone: 'live' },
      { name: '추천 카드 최대 5건 · 관련도순', state: '구현', tone: 'live' },
      { name: '제공처별 전용 필터(출처·업력·대상·연령)', state: '구현', tone: 'live' },
      { name: 'K-Startup 수집·색인', state: '기본 OFF', tone: 'part' },
      { name: '검색 준비 상태 안내', state: '구현', tone: 'live' },
      { name: 'Elasticsearch Nori·BM25 + Qdrant RRF 결합', state: '구현', tone: 'live' },
      { name: '도우미 자유 질문 위젯', state: '구현', tone: 'live' },
      { name: '하이브리드 검색 개발 Docker 배포', state: '미배포', tone: 'part' },
      { name: '공고 비교 담기 버튼', state: '시안만', tone: 'gap' },
      { name: '대화 기록 저장·다시 보기·삭제', state: '구현', tone: 'live' },
      { name: '비회원 검색 결과 로그인 후 복원(Redis)', state: '구현', tone: 'live' },
    ],
    next: ['하이브리드 검색을 개발 Docker에 배포(V24 적용·두 색인 복구)', 'K-Startup 실데이터 활성화 후 추가 가치 비교', '검색 결과 0건일 때 다음 행동 제안 문구'],
    questions: ['필터 검색과 AI 대화 검색 중 기본 진입은 어느 쪽인가?', '적합도 점수를 숫자로 계속 노출할지, 등급으로 바꿀지'],
    history: [
      { date: '2026-09-14', who: '김동섭', what: '계정별 대화 기록 저장·다시 보기·삭제 추가', ref: 'main 통합' },
      { date: '2026-09-14', who: '김동섭', what: '비회원 검색 결과를 Redis에 보관해 로그인 후 복원', ref: 'redis-search-result-restoration' },
      { date: '2026-09-13', who: '김건우', what: '도우미 자유 질문 위젯 — 의도 분류·인용 검증·개인정보 마스킹·화면 이동 버튼(검색은 실행하지 않음)', ref: 'evaluation/assistant' },
      { date: '2026-09-12', who: '김건우', what: '단순 키워드 매칭을 Elasticsearch Nori·BM25로 교체, Qdrant 의미 후보와 RRF 결합(각 20개)', ref: 'V24 · elasticsearch-lexical-search' },
      { date: '2026-09-09', who: '김건우', what: 'K-Startup 실제 API Client·정규화·제공처별 동기화와 전용 필터 추가(기본 수집 비활성)', ref: 'main 통합' },
      { date: '2026-09-08', who: '김건우', what: '필터 검색과 지역·분야 선택 목록 추가, 로그인 경로 충돌 해결', ref: 'PR #115' },
      { date: '2026-09-08', who: '김건우', what: '첫 메시지 후 입력창 하단 고정, 로딩 애니메이션 추가', ref: 'PR #105 · #107' },
      { date: '2026-09-08', who: '김건우', what: '밝은 배경 + 녹색 포인트로 테마 재조정', ref: 'PR #103' },
      { date: '2026-09-07', who: '김건우', what: '조건·상태 패널 제거, 확인 화면 간소화', ref: 'PR #83' },
      { date: '2026-09-07', who: '김건우', what: '대화로 조건을 바꾸는 제안·확인 검색 도입', ref: 'PR #78' },
      { date: '2026-09-05', who: '김건우', what: '전체 공고 의미 검색과 Qdrant 색인 구현', ref: 'PR #9 · 이슈 #10' },
    ],
  },
  {
    no: '02', key: 'program-detail', group: '검색', name: '공고 상세', route: '/app/support-programs/detail', owner: '김건우',
    prio: 'P2', prioWhy: '동작이 안정적이라 발표 전 손댈 것이 없습니다',
    tagline: '판단과 근거를 함께 보여 주는, 이 제품의 신뢰 담당 화면', status: '구현 완료', tone: 'live',
    demo: true, notes: [],
    lastChanged: '2026-09-08',
    biz: '추천만 하는 서비스는 많고, 틀리면 바로 신뢰를 잃습니다. 이 화면은 "왜 이 공고인가"를 공식 원문 문장으로 되돌려 주는 자리입니다. 관련도와 신청 자격을 분리하고 모르면 모른다고 표시하는 원칙이 여기서 지켜지지 않으면 나머지 화면의 숫자도 의미가 없습니다.',
    value: ['확인 필요 배지를 보고도 상세로 들어오는 비율', '원문 질문까지 이어지는 비율', '잘못된 자격 판정 신고 0건'],
    elements: [
      { name: '자격 검토 결과 배지', state: '구현', tone: 'live' },
      { name: '지역·대상 판정 근거 인용', state: '구현', tone: 'live' },
      { name: 'URL 직접 접속·새로고침', state: '구현', tone: 'live' },
      { name: '공식 원문 링크(호스트 검증)', state: '구현', tone: 'live' },
      { name: '첨부문서 기반 확인', state: '미구현', tone: 'gap' },
      { name: '체크리스트형 요건 대조', state: '시안만', tone: 'gap' },
    ],
    next: ['첨부 미검증 표기 위치 통일', '요건 체크리스트 도입 여부 결정'],
    questions: ['요건을 체크리스트로 분해할지, 원문 인용만 유지할지'],
    history: [
      { date: '2026-09-08', who: '김건우', what: '검색 관련성과 신청 자격 분리, 추천 정확도 개선', ref: 'PR #87' },
      { date: '2026-09-08', who: '김건우', what: '자격 주의문 대비 1.68:1 → 5.93:1 수정', ref: 'UI-11' },
      { date: '2026-09-07', who: '김건우', what: '원문 기반 지역 자격 판정 개선(상·하위 지역, 이전 허용 대안)', ref: 'PR #79' },
      { date: '2026-09-05', who: '김건우', what: '공고 상세 조회 API와 URL 기반 화면 구현', ref: 'PR #14' },
    ],
  },
  {
    no: '03', key: 'program-question', group: '검색', name: '공고 원문 질문', route: '…/detail/question', owner: '김건우',
    prio: 'P2', prioWhy: '기업마당 한정이라는 범위만 발표에서 말하면 됩니다',
    tagline: '공식 원문에 직접 묻고 인용으로 답을 받는 화면', status: '구현 완료 · 기업마당 한정', tone: 'part',
    demo: true, notes: [],
    lastChanged: '2026-09-07',
    biz: '자격 판정이 애매할 때 담당자는 결국 공고 원문을 읽습니다. 이 화면은 그 읽기를 대신해 주되, 답변마다 원문 인용을 붙여 근거를 남깁니다. 근거가 부족하면 "부족하다"고 답하는 것이 이 기능의 계약입니다.',
    value: ['질문 1건당 인용을 열어 보는 비율', '근거 부족 응답 후 원문으로 이동하는 비율'],
    elements: [
      { name: '질문 입력·500자 제한', state: '구현', tone: 'live' },
      { name: '원문 인용 번호 선택', state: '구현', tone: 'live' },
      { name: '근거 부족 상태 표시', state: '구현', tone: 'live' },
      { name: '70초 시간 초과·입력 보존', state: '구현', tone: 'live' },
      { name: 'K-Startup 원문 질문', state: '미지원', tone: 'gap' },
      { name: '첨부·PDF 기반 답변', state: '미구현', tone: 'gap' },
    ],
    next: ['미지원 제공처 차단 안내 문구 재작성', '첨부 기반 RAG 범위 결정'],
    questions: ['기업마당 외 제공처는 질문을 아예 숨길지, 비활성으로 보여줄지'],
    history: [
      { date: '2026-09-07', who: '김건우', what: '대상 조건 요약 누락 보완 — 가상 6건·공식 6건 재검증', ref: '5단계 v2' },
      { date: '2026-09-07', who: '김건우', what: 'RAG 인용 오류 수정(64자리 ID → 번호 선택·ID 복원)', ref: 'PR #57' },
      { date: '2026-09-07', who: '김건우', what: '기업마당 공식 HTML 수집·청킹·근거 인용 RAG 최소 구현', ref: '5단계' },
    ],
  },

  // ── 분석·문서 ──────────────────────────────────────────
  {
    no: '04', key: 'application-prep', group: '분석·문서', name: '신청 문서 작성', route: '/app/application-preparations', owner: '김동섭',
    prio: 'P0', prioWhy: '가장 큰 차별화 기능인데 모든 양식의 배치 정확성을 보장하지 않아, 시연 공고를 미리 골라 기입 결과를 확인해야 합니다',
    tagline: '공식 서식을 찾아 답변을 기입하고 같은 형식으로 내려받는 화면', status: '구현 완료 · 배치 정확성 미보장', tone: 'part',
    demo: true, notes: [],
    lastChanged: '2026-09-13',
    biz: '공고를 찾고 자격을 확인해도 마지막 관문은 서류입니다. 관심 공고함에서 바로 고르거나 전체 공고를 검색해 공식 PDF·HWP·HWPX를 분석하고, 문항을 발견해 답변을 받아 원본 서식에 기입한 파일을 같은 형식으로 내려줍니다. 검색 → 담기 → 신청까지 하나로 이어지는 유일한 경로이자 이 제품의 종착점입니다.',
    value: ['준비 건당 문서 다운로드 완료율', '관심 공고함 → 준비 건 생성 전환율', '사실 확인에서 오류로 되돌아오는 비율'],
    elements: [
      { name: '관심 공고함·전체 공고 검색에서 선택', state: '구현', tone: 'live' },
      { name: '중복 검토와 상호 연동', state: '구현', tone: 'live' },
      { name: '공식 PDF/HWP/HWPX 양식 발견', state: '구현', tone: 'live' },
      { name: '4개 제공처 지원(기업마당·K-Startup·과기정통부·충남)', state: '구현', tone: 'live' },
      { name: '문항 질문·답변 입력', state: '구현', tone: 'live' },
      { name: '원문 인용 사실 확인·정규화', state: '구현', tone: 'live' },
      { name: '원본 서식에 기입·같은 형식 다운로드', state: '구현', tone: 'live' },
      { name: '저장 목록·본인 건 삭제(cascade)', state: '구현', tone: 'live' },
      { name: '전 양식 기입 위치 정확성', state: '미보장', tone: 'part' },
      { name: '암호화 문서·임의 업로드·스캔 PDF', state: '미지원', tone: 'gap' },
    ],
    next: ['기입 위치 누락 사례 수집 후 양식별 보정', '지원 제공처 추가 범위 결정'],
    questions: ['기입 위치가 틀릴 수 있다는 점을 화면에서 어떻게 알릴 것인가?', '스캔 PDF 공고는 안내로 막을지, 수동 입력으로 우회할지'],
    history: [
      { date: '2026-09-14', who: '김동섭', what: '전체 흐름 안정화 — 로그인 복귀·세션 격리·장애 처리 보완', ref: 'skn-142·145~147 · #297~#303' },
      { date: '2026-09-13', who: '김동섭', what: '원본 문서 생성·다운로드 — 입력/결과 페이지 분리, 원본 형식 기입, 입력 수정 후 재생성(V32)', ref: 'skn-140 · #285' },
      { date: '2026-09-13', who: '김동섭', what: '공식 문서 분석을 V26 Outbox·RabbitMQ 작업으로 접수, 최근 작업·상태 자동 조회·결과 복원', ref: 'V26 · skn-128 · #267' },
      { date: '2026-09-12', who: '김동섭', what: '관심 공고 선택 팝업을 중복 검토와 공유', ref: 'skn-121 · #246' },
      { date: '2026-09-12', who: '김동섭', what: '전 제공처 공식 첨부 지원 — 기업마당·K-Startup·과기정통부·충남 수출지원', ref: 'skn-112 · #230' },
      { date: '2026-09-12', who: '김동섭', what: '단계 분리·제공처 확장 / 발견 오류·삭제·선택 흐름 보강', ref: 'skn-102·103 · #210·#212' },
      { date: '2026-09-11', who: '김동섭', what: '작성 도우미 공고 검색 — 전체 제공처 공고 검색·선택, URL·ID 입력은 보조 경로', ref: 'skn-100 · #207' },
      { date: '2026-09-11', who: '김동섭', what: '공고 기반 양식 발견 전환 — 공식 첨부 수집·문항 추출·버전 스냅샷', ref: 'skn-96 · #199' },
      { date: '2026-09-11', who: '김동섭', what: '문항별 질문과 사실 확인 — AI 답변 해석, 사실 제안·확인, 문항 입력 저장', ref: 'skn-92 · #189' },
      { date: '2026-09-10', who: '김동섭', what: '신청 준비 기본 흐름 — 검수 양식과 준비 건 생성·목록·상세', ref: 'skn-90 · #187' },
      { date: '2026-09-10', who: '김동섭', what: '제약·계약 확정 — 설계 문서, 공식 대상·범위·공개/AI 계약', ref: 'skn-89 · #185' },
    ],
  },
  {
    no: '05', key: 'combination-review', group: '분석·문서', name: '중복 지원·수혜 검토', route: '/app/combination-reviews', owner: '김동섭',
    prio: 'P0', prioWhy: '비동기 전환 후 개발 Docker 미배포 — 배포 전에는 시연에서 202만 보이고 결과가 안 나옵니다',
    tagline: '사업 2~3개를 함께 신청할 수 있는지 공식 근거로 대조', status: '구현 완료 · 품질 미검증', tone: 'part',
    demo: true, notes: [],
    lastChanged: '2026-09-12',
    biz: '지원사업은 중복 신청·중복 수혜 제한이 공고마다 다르게 흩어져 있어, 담당자가 두세 개를 함께 신청할 수 있는지 스스로 판단하기 어렵습니다. 사업과 지원 상태를 입력하면 공식 첨부(PDF·HWPX)를 자동 수집해 신청·선정·확약·협약·수행·교부 여섯 단계별 제한·허용 범위·미확인 사항을 인용과 함께 보여 줍니다.',
    value: ['검토 실행 후 원문 인용을 열어 보는 비율', '미확인 사항을 확인해 재검토하는 비율', '기관 문의 없이 판단이 끝난 비율'],
    elements: [
      { name: '검토 목록 · 커서 더 보기', state: '구현', tone: 'live' },
      { name: '관심 공고·신청 준비와 연동', state: '구현', tone: 'live' },
      { name: '새 검토 · 공고 2~3개 선택', state: '구현', tone: 'live' },
      { name: '입력 수정(409 보존)·분석 실행', state: '구현', tone: 'live' },
      { name: '자동 첨부 수집·PDF/HWPX 파싱', state: '구현', tone: 'live' },
      { name: '여섯 단계 판단·인용·원본 다운로드', state: '구현', tone: 'live' },
      { name: '실제 모델 품질·사람 검수', state: '미검증', tone: 'gap' },
      { name: 'K-Startup·세부사업 ID', state: '미지원', tone: 'gap' },
    ],
    next: ['Core 실행 이미지 재빌드로 V25 migration 반영 후 COMBINATION_REVIEW_QUEUE_ENABLED 확인', '투자연계형 원문·정산/반환 지침 확보', '사람 검수 정답 확보 후 18개 사례 정확도 측정'],
    questions: ['무료 티어에서 검토 실행 횟수를 제한할 것인가?', '자동 수집이 실패한 공고는 검토를 막을지, 범위 표시로 진행할지'],
    history: [
      { date: '2026-09-12', who: '김동섭', what: '관심 공고 선택 UI 도입 — 신청 문서 작성과 선택 팝업 공유', ref: 'skn-121 · #246' },
      { date: '2026-09-12', who: '김동섭', what: '전 제공처 공식 첨부 수집으로 검토 범위 확대', ref: 'skn-112 · #230' },
      { date: '2026-09-12', who: '김동섭', what: '동기 HTTP를 202 접수 → RabbitMQ → 내부 소비자 → DB 조회로 전환, UNKNOWN 보존·중복 실행 차단', ref: 'V25 · skn-128 · #267' },
      { date: '2026-09-09', who: '김동섭', what: 'PUT 204 계약 불일치 수정, COMBINATION_REVIEW_NOT_FOUND 구분 (Frontend 559개 통과)', ref: 'skn-59 · #123' },
      { date: '2026-09-09', who: '김동섭', what: '5-1 사용자 화면 — 목록·새 검토·입력 수정·분석 실행·실행 이력 5화면 연결', ref: 'skn-59 · #123' },
      { date: '2026-09-09', who: '김동섭', what: '4-2~4-4 자동 첨부 수집·PDF/HWPX 파싱·단일 Agent (Core 723개·AI 725개 통과)', ref: 'skn-59 · #123' },
      { date: '2026-09-09', who: '김동섭', what: '4-1 공식 근거 고정 — 중기부 HWPX 2개·인용 12개·가상 입력 18개', ref: 'skn-59 · #123' },
      { date: '2026-09-09', who: '김동섭', what: '3-1~3-2 Domain·MyBatis 저장 경로와 인증 기반 입력 API (Core 681개 통과)', ref: 'skn-59 · #123' },
    ],
  },
  {
    no: '06', key: 'daily-report', group: '분석·문서', name: '기업 맞춤 리포트', route: '/app/reports · /report-email', owner: '김건우',
    prio: 'P1', prioWhy: '자동 발송이 기본 비활성이라 시연은 웹 미리보기로 대체 가능합니다',
    tagline: '저장된 기업 조건으로 매일 추천을 보내는 화면 — 리텐션 장치', status: '구현 완료 · 실전달 검증 별도', tone: 'part',
    demo: true, notes: [],
    lastChanged: '2026-09-09',
    biz: '관심 공고·알림이 하려던 "다시 찾아올 이유"를 이 기능이 먼저 가져갔습니다. 저장된 기업의 지역·업종·지원 목적으로 최대 3건을 골라 기업마당 원문 근거와 서류 확인을 붙여 보냅니다. 웹 미리보기와 SMTP 정기 발송, 수신 확인·동의·해지가 모두 있고 자동 발송만 기본 비활성입니다.',
    value: ['리포트 열람 후 재방문 비율', '수신 동의 유지율', '리포트 경유 상세 조회 수'],
    elements: [
      { name: '리포트 웹 미리보기', state: '구현', tone: 'live' },
      { name: '최대 3건 추천 + 원문 근거', state: '구현', tone: 'live' },
      { name: 'SMTP 정기 발송', state: '구현', tone: 'live' },
      { name: '수신 확인·동의·해지', state: '구현', tone: 'live' },
      { name: '자동 발송 활성화', state: '기본 비활성', tone: 'part' },
      { name: '실제 전달률·도착 검증', state: '미검증', tone: 'gap' },
      { name: '선정 확률·뉴스·첨부 분석', state: '범위 제외', tone: 'gap' },
    ],
    next: ['자동 발송 활성화 시점과 발송 시각 결정', '실제 메일 전달률 검증', '관심 공고함과 역할 정리'],
    questions: ['일일 리포트가 있으면 관심 공고함은 여전히 필요한가?', '무료 티어에 리포트를 포함할 것인가?'],
    history: [
      { date: '2026-09-13', who: '김건우', what: '리포트 메일 발송을 생성과 별도 큐로 분리(V27 발송 Outbox 컬럼), 관리자 조회에 daily-report-delivery 추가', ref: 'V27 · rabbitmq-daily-report-delivery' },
      { date: '2026-09-12', who: '김건우', what: '리포트 생성에 MySQL Outbox·RabbitMQ 적용 — 조건부 선점으로 중복 처리, UNKNOWN 작업 재시도 차단', ref: 'rabbitmq-daily-report-generation' },
      { date: '2026-09-09', who: '김건우', what: '기업 맞춤 일일 리포트 추가 — 추천 3건·원문 근거·미리보기·SMTP·수신 관리', ref: 'daily-reports' },
    ],
  },
  {
    no: '07', key: 'watchlist', group: '분석·문서', name: '관심 공고함', route: '/app/saved-programs', owner: '송승재',
    prio: 'P1', prioWhy: '담기·목록은 되니 시연 가능. 마감 알림은 발표 후',
    tagline: '마감 전까지 이어지는 관리 — 공고를 담아 두는 화면', status: '구현 완료', tone: 'live',
    demo: true, notes: [],
    lastChanged: '2026-09-13',
    biz: '지원사업은 마감일이 있는 일정입니다. 공고 상세에서 담으면 /app/saved-programs에 최근 순서로 쌓이고, 신청 문서 작성에서 바로 골라 쓸 수 있어 검색 → 담기 → 문서 준비가 하나로 이어집니다. 공고 내용은 저장하지 않고 조회 때 현재 공고를 읽어 접수 상태를 맞춥니다. 남은 것은 마감 알림입니다.',
    value: ['관심 공고 1건 이상 보유한 계정 비율', '마감 3일 전 알림 열람률'],
    elements: [
      { name: '담기·빼기 (V22 saved_support_program)', state: '구현', tone: 'live' },
      { name: '목록 · 최근 순서·접수 상태 동기화', state: '구현', tone: 'live' },
      { name: '신청 문서 작성에서 바로 선택', state: '구현', tone: 'live' },
      { name: '관심 공고 일정 달력', state: '구현', tone: 'live' },
      { name: '신청 준비·중복 검토 연동', state: '구현', tone: 'live' },
      { name: '비로그인 상세 · 로그인 링크', state: '구현', tone: 'live' },
      { name: '마감 알림 발송', state: '미구현', tone: 'gap' },
      { name: '목록에서 빼기 UI', state: '미구현', tone: 'gap' },
      { name: '마감 D-day 표시(달력에 포함)', state: '구현', tone: 'live' },
    ],
    next: ['마감 알림 채널·시점 결정 후 착수', '목록에서 직접 빼기 버튼 추가'],
    questions: ['일일 리포트와 관심 공고함의 알림 역할을 어떻게 나눌 것인가?', '마감 알림은 며칠 전부터 보낼 것인가?'],
    history: [
      { date: '2026-09-14', who: '송승재', what: '관심 공고 일정 달력 추가, 신청 준비·중복 검토와 상호 연동', ref: 'main 통합' },
      { date: '2026-09-13', who: '김건우', what: '관심 공고함 구현 — 담기·빼기 API와 /app/saved-programs 목록, 신청 문서 작성 연동', ref: 'V22 · main 통합' },
      { date: '2026-09-06', who: '팀원 시안', what: 'UI Explorer 시안에 관심 공고·알림 화면으로 정의됨', ref: '외부 시안 · 착수 전' },
    ],
  },

  // ── 협업 ──────────────────────────────────────────────
  {
    no: '08', key: 'partners', group: '협업', name: '파트너 관리 · 모집글', route: '/app/partners · /partners', owner: '김건우',
    prio: 'P2', prioWhy: '숨김·신고는 발표 범위 밖입니다',
    tagline: '컨소시엄 파트너를 찾는 모집글 목록·작성·상세', status: '구현 완료', tone: 'live',
    demo: false, notes: [],
    lastChanged: '2026-09-11',
    biz: 'R&D·컨소시엄형 공고는 혼자 신청할 수 없어 파트너 탐색 수요가 실제로 있습니다. 기업을 등록한 회원이 접수 중 공고 하나에 모집글을 쓰고(공고당 하나), 누구나 검색어·역할·지역·정렬로 찾습니다. 비로그인 화면에서는 작성 기업 정보를 흐리게 가려 가입 동기를 만듭니다.',
    value: ['모집글당 제안 수', '비로그인 → 로그인 전환율', '모집 중 글 대비 마감 처리율'],
    elements: [
      { name: '목록 · 검색·역할·지역 필터·정렬·페이지', state: '구현', tone: 'live' },
      { name: '작성·수정·수동 마감', state: '구현', tone: 'live' },
      { name: '공용 머리글 · 모집글/내 모집글/제안함 탭', state: '구현', tone: 'live' },
      { name: '비로그인 흐림 처리 · 로그인 다이얼로그', state: '구현', tone: 'live' },
      { name: '카드 격자 3·2·1열 반응형', state: '구현', tone: 'live' },
      { name: '숨김·신고', state: '미구현', tone: 'gap' },
      { name: '제안 알림 발송', state: '미구현', tone: 'gap' },
    ],
    next: ['숨김·신고 기능 범위 결정', '제안 알림은 이메일 인증 이후 착수'],
    questions: ['출시 1차 범위에 파트너 관리를 포함할 것인가?'],
    history: [
      { date: '2026-09-12', who: '김건우', what: '사이드바 계정 카드를 메뉴 버튼으로 정리, 오른쪽 빈 띠 제거, 인증 태그 제거·카드 3열 고정', ref: 'main 통합' },
      { date: '2026-09-11', who: '김건우', what: '공용 머리글(WorkspacePageHeader) 도입, 예시 매칭 카드·안내 문구 제거, 도움말 말풍선으로 정리', ref: 'main 통합' },
      { date: '2026-09-10', who: '김건우', what: '모집글 수정·수동 마감 추가, 비로그인 공개 화면 흐림 처리와 로그인 복귀 다이얼로그', ref: 'main 통합' },
      { date: '2026-09-09', who: '김건우', what: '실제 등록·저장(공고당 1건), 검색·역할·지역 필터·정렬·페이지 연결', ref: 'main 통합' },
      { date: '2026-09-08', who: '이성민', what: '공개 파트너 모집 목록·상세 추가', ref: 'PR #112' },
      { date: '2026-09-08', who: '김건우', what: '모집 상세 링크 오연결 수정, 마감일 검증 추가', ref: 'UI-15 · UI-16' },
      { date: '2026-09-08', who: '이성민', what: '모집 목록·작성 화면 최초 추가', ref: 'PR #89' },
    ],
  },
  {
    no: '09', key: 'partners-mine', group: '협업', name: '내 모집글', route: '/app/partners/mine', owner: '김건우',
    prio: 'P2', prioWhy: '모집글 탭은 완료 상태입니다',
    tagline: '내가 쓴 모집글을 모아 수정·마감하는 탭', status: '구현 완료', tone: 'live',
    demo: false, notes: [],
    lastChanged: '2026-09-10',
    biz: '모집글은 쓰고 끝나는 글이 아니라 마감까지 관리해야 하는 대상입니다. 목록에 섞여 있으면 내 글을 찾기 어려워 방치되므로, 별도 탭으로 분리해 최근 등록순으로 모으고 마감된 글은 뒤로 보냅니다.',
    value: ['모집 중 글 대비 마감 처리 비율', '작성 후 수정 발생률'],
    elements: [
      { name: '내 글 최근 등록순 목록', state: '구현', tone: 'live' },
      { name: '마감된 글 뒤로 정렬', state: '구현', tone: 'live' },
      { name: '카드에서 수정·마감', state: '구현', tone: 'live' },
      { name: '마감 확인 상자', state: '구현', tone: 'live' },
    ],
    next: ['마감 임박 표시 추가 여부'],
    questions: ['마감된 글을 일정 기간 뒤 자동으로 숨길 것인가?'],
    history: [
      { date: '2026-09-10', who: '김건우', what: '내 모집글 탭 추가 — 목록의 "내가 쓴 모집글만" 칩을 대체', ref: 'main 통합' },
    ],
  },
  {
    no: '10', key: 'proposals', group: '협업', name: '제안함', route: '/app/proposals', owner: '김건우',
    prio: 'P2', prioWhy: '제안 알림만 남아 발표에는 영향 없습니다',
    tagline: '보낸·받은 파트너 제안을 한곳에서 처리', status: '구현 완료', tone: 'live',
    demo: false, notes: [],
    lastChanged: '2026-09-09',
    biz: '파트너 모집이 실제로 동작하려면 제안을 주고받은 뒤의 처리 화면이 필요합니다. 대기·수락·거절·철회·만료를 조회 시점에 계산하고, 담당자 이메일과 기업 기본정보는 수락된 뒤에만 서로 공개합니다. 7일 무응답이면 자동 만료되어 방치된 제안이 쌓이지 않습니다.',
    value: ['제안 수신 후 응답까지 걸린 시간', '7일 만료 전 응답 비율', '수락 후 실제 연락으로 이어진 비율'],
    elements: [
      { name: '보낸·받은 제안함 탭', state: '구현', tone: 'live' },
      { name: '수락·거절·철회', state: '구현', tone: 'live' },
      { name: '상태 계산(대기·수락·거절·철회·만료)', state: '구현', tone: 'live' },
      { name: '수락 후 연락처 상호 공개', state: '구현', tone: 'live' },
      { name: '사이드바 대기 건수 배지', state: '구현', tone: 'live' },
      { name: '제안 도착 이메일 알림', state: '미구현', tone: 'gap' },
    ],
    next: ['제안 알림 발송 채널 결정', '만료 임박 안내 표시 여부'],
    questions: ['7일 응답 기한을 사용자가 조정할 수 있게 할 것인가?'],
    history: [
      { date: '2026-09-09', who: '김건우', what: '제안함 화면과 API 추가 — Redux receivedProposals로 세 곳이 상태 공유', ref: 'main 통합' },
    ],
  },

  // ── 계정 ──────────────────────────────────────────────
  {
    no: '11', key: 'profile', group: '계정', name: '내 프로필', route: '/app/profile', owner: '이성민',
    prio: 'P1', prioWhy: '알림 설정 스위치가 저장되지 않는 점을 시연 중 언급할지 정해야 합니다',
    tagline: '개인화의 시작점 — 기업 등록과 협업 설정을 저장', status: '구현 완료', tone: 'live',
    demo: true, notes: [],
    lastChanged: '2026-09-11',
    biz: '지역·업종·설립연도는 검색 정확도와 리포트 추천을 좌우하는 값입니다. 사업자등록번호를 Bizno로 확인해 기업을 등록하면 tier가 COMPANY로 올라가고, 협업·파트너 설정과 프로필 완성도까지 실제로 저장됩니다. 시안의 마이페이지 역할도 이 화면이 흡수했습니다.',
    value: ['가입자 중 기업 등록을 마친 비율', '두 번째 방문에서 조건을 다시 쓰지 않는 비율', '프로필 완성도 80% 이상 비율'],
    elements: [
      { name: '기업 등록·기본정보 저장', state: '구현', tone: 'live' },
      { name: '사업자등록번호 확인(Bizno)', state: '구현', tone: 'live' },
      { name: '협업·파트너 설정 저장', state: '구현', tone: 'live' },
      { name: '프로필 완성도 체크리스트', state: '구현', tone: 'live' },
      { name: '비밀번호 변경·계정 삭제 모달', state: '구현', tone: 'live' },
      { name: '알림 설정 스위치 3개', state: '화면만', tone: 'part' },
      { name: '우대·인증 자격, 북마크', state: '제거됨', tone: 'gap' },
      { name: '검색 조건과의 자동 연결', state: '미구현', tone: 'gap' },
    ],
    next: ['알림 설정 저장 API 연결(발송 기능 이후)', '저장 프로필과 대화 조건의 우선순위 규칙 정의', '기업 인증 단계 도입 여부 결정'],
    questions: ['프로필을 바꾸면 진행 중인 검색 조건도 바뀌어야 하나?', '알림 설정을 저장 없이 계속 노출할 것인가?'],
    history: [
      { date: '2026-09-13', who: '김건우', what: '비밀번호 없는 소셜 계정은 비밀번호 항목을 숨기고 세션만으로 계정 삭제 확인', ref: 'main 통합' },
      { date: '2026-09-11', who: '김건우', what: '카드 레이아웃 한 칸으로 정리 — 옆 칸 설명을 ? 도움말로 옮기고 완성도는 요약 카드 아래로', ref: 'main 통합' },
      { date: '2026-09-09', who: '김건우', what: '기업 등록·기본정보 저장, 사업자등록번호 Bizno 확인, 협업·파트너 설정 저장 연결', ref: 'main 통합' },
      { date: '2026-09-09', who: '김건우', what: '비밀번호 변경·계정 삭제 모달 연결, 우대·인증 자격·북마크 제거', ref: 'main 통합' },
      { date: '2026-09-08', who: '김건우', what: '미저장·데모 상태를 화면에 명시, 미연결 버튼 비활성화', ref: 'UI-17 · UI-20' },
      { date: '2026-09-08', who: '이성민', what: '프로필 화면 최초 추가(예시 데이터)', ref: 'PR #89' },
    ],
  },
  {
    no: '12', key: 'auth', group: '계정', name: '로그인 · 회원가입', route: '/login · /signup', owner: '이성민',
    prio: 'P0', prioWhy: '소셜 로그인이 실제 공급자 앱 등록 전이라, 시연에서 카카오·Google 버튼을 누르면 실패합니다',
    tagline: '내 정보를 이어서 쓰기 위한 최소한의 관문', status: '구현 완료', tone: 'live',
    demo: true, notes: [],
    lastChanged: '2026-09-13',
    biz: '가입 자체가 목적이 아니라 저장·리포트·파트너 제안을 쓰기 위한 전제입니다. 이제 카카오·Google 소셜 로그인과 이메일 인증번호까지 갖춰, 비밀번호를 만들지 않고도 가입할 수 있습니다. 가입 이탈이 곧 나머지 기능 전체의 상한선이라 이 경로를 늘린 것이 지난주 가장 큰 변화입니다.',
    value: ['가입 시작 대비 완료율', '가입 직후 첫 검색까지의 시간', '로그인 실패 후 복구 성공률'],
    elements: [
      { name: '이메일 로그인·세션(HttpOnly 쿠키)', state: '구현', tone: 'live' },
      { name: '회원가입 + 입력 검증', state: '구현', tone: 'live' },
      { name: '보호 경로·권한 가드', state: '구현', tone: 'live' },
      { name: '로그인 시도 제한·계정 잠금', state: '구현', tone: 'live' },
      { name: '비밀번호 찾기 링크', state: '구현', tone: 'live' },
      { name: '이메일 인증번호(6자리·통행 토큰)', state: '구현', tone: 'live' },
      { name: '카카오·Google 소셜 로그인·가입', state: '구현', tone: 'live' },
      { name: '개발용 시드 로그인', state: '개발 전용', tone: 'part' },
      { name: '실제 공급자 연결 검증', state: '미검증', tone: 'part' },
      { name: '로그인 후 소셜 계정 연결·해제 화면', state: '미구현', tone: 'gap' },
    ],
    next: ['실제 카카오·Google 앱 등록 후 콜백 검증', '로그인 상태에서 소셜 연결·해제 화면 설계', '프로덕션 빌드에서 개발 로그인 버튼 차단 확인'],
    questions: ['같은 이메일의 기존 계정에 소셜 계정을 자동 연결할 것인가?'],
    history: [
      { date: '2026-09-13', who: '김건우', what: '카카오 탈퇴 연결 해제를 V28 작업·RabbitMQ worker로 처리, 성공 전 동일 identity 재가입 차단', ref: 'V28 · rabbitmq-account-oauth-unlink' },
      { date: '2026-09-12', who: '김건우', what: '카카오·Google OAuth 2.0 + OIDC 직접 구현 — state·nonce·PKCE, /oauth/complete 화면', ref: 'V17 · main 통합' },
      { date: '2026-09-12', who: '김건우', what: '이메일 인증번호 6자리 발급·확인과 통행 토큰으로 가입 시 인증 완료 기록', ref: 'main 통합' },
      { date: '2026-09-09', who: '김건우', what: '로그인 화면에 비밀번호 찾기 링크 추가', ref: 'main 통합' },
      { date: '2026-09-08', who: '이성민', what: '로그인 상태별 화면 분리, 공개 파트너 모집 화면 추가', ref: 'PR #112' },
      { date: '2026-09-08', who: '이성민', what: '로그인 세션 연결과 화면 권한 보호 추가', ref: 'PR #111' },
      { date: '2026-09-08', who: '김건우', what: '가입 폼 검증 추가(형식·길이·확인 일치)', ref: 'UI-13' },
      { date: '2026-09-08', who: '이성민', what: '로그인·회원가입 화면 최초 추가', ref: 'PR #89' },
    ],
  },
  {
    no: '13', key: 'password-reset', group: '계정', name: '비밀번호 재설정', route: '/forgot-password · /reset-password', owner: '이성민',
    prio: 'P2', prioWhy: 'SMTP 없으면 로그 대체로 동작합니다',
    tagline: '로그인 못 하는 사용자를 되돌리는 최소 복구 경로', status: '구현 완료', tone: 'live',
    demo: false, notes: [],
    lastChanged: '2026-09-09',
    biz: '가입은 되는데 로그인이 안 되면 그 계정은 그대로 이탈합니다. 이 경로가 없으면 저장된 기업 정보·검토 이력·제안이 모두 잠깁니다. 가입 여부와 무관하게 204를 돌려 계정 존재를 노출하지 않고, 30분 일회용 토큰의 해시만 저장합니다.',
    value: ['재설정 요청 후 로그인 성공률', '재설정 메일 클릭률'],
    elements: [
      { name: '재설정 요청(/forgot-password)', state: '구현', tone: 'live' },
      { name: '새 비밀번호 설정(/reset-password)', state: '구현', tone: 'live' },
      { name: '30분 일회용 토큰·해시 저장', state: '구현', tone: 'live' },
      { name: '확인 후 전체 세션 삭제', state: '구현', tone: 'live' },
      { name: '계정당 시간당 3회 제한', state: '구현', tone: 'live' },
      { name: 'SMTP 없을 때 로그 대체', state: '개발 전용', tone: 'part' },
    ],
    next: ['운영 SMTP 확정 후 실제 메일 도착 확인'],
    questions: ['재설정 후 기존 로그인 세션을 모두 끊는 정책을 유지할 것인가?'],
    history: [
      { date: '2026-09-09', who: '김건우', what: '비밀번호 재설정 추가 — V14 account_password_reset, 30분 일회용 토큰', ref: 'main 통합' },
    ],
  },

  // ── 운영 ──────────────────────────────────────────────
  {
    no: '14', key: 'pricing', group: '운영', name: '요금제', route: '/app/pricing · /pricing', owner: '김건우',
    prio: 'P2', prioWhy: '유료 경계 미정 — 발표에서는 화면만 보여 줍니다',
    tagline: '과금 모델의 자리 — 유료 경계는 미정', status: '부분 구현', tone: 'part',
    demo: false, notes: [],
    lastChanged: '2026-09-08',
    biz: '무료·프로·팀 3단계 소개가 이미 화면으로 존재합니다. 다만 무엇을 유료로 가를지가 정해지지 않았습니다. 리포트 발송, 중복 검토 실행 횟수, 관심 공고 수 중 어디에 선을 그을지가 여러 화면의 설계를 바꿉니다.',
    value: ['요금제 조회 후 가입 전환율', '문의 전환 수'],
    elements: [
      { name: '3단계 요금 소개', state: '구현', tone: 'live' },
      { name: '결제 연동', state: '미구현', tone: 'gap' },
      { name: '기능별 제한 정의', state: '미정', tone: 'gap' },
    ],
    next: ['유료 경계 항목 확정(리포트·중복 검토·관심 공고 중)', 'CTA를 결제로 둘지 문의로 둘지 결정'],
    questions: ['무료 티어에서 검색·검토 횟수를 제한할 것인가?'],
    history: [
      { date: '2026-09-08', who: '김건우', what: '무료·프로·팀 요금제 소개 페이지 추가', ref: 'PR #100' },
    ],
  },
  {
    no: '15', key: 'admin', group: '운영', name: '어드민 · 회원·기업', route: '/app/admin/members', owner: '이성민',
    prio: 'P1', prioWhy: '회원 조치는 완료. 큐 위젯은 발표 후',
    tagline: '회원을 조치하고 큐 상태를 확인하는 내부 화면', status: '구현 완료 · 위젯 미구현', tone: 'part',
    demo: false, notes: [],
    lastChanged: '2026-09-13',
    biz: '공고 수집·색인이나 작업 큐가 멈추면 사용자는 빈 결과만 보게 됩니다. 이제 회원 요약·목록·상세와 정지·정지 해제·강제 로그아웃이 사유 기록과 함께 동작하고, 관리자 전용 읽기 API로 리포트·중복 검토·문서 분석 큐의 DB 상태와 브로커 현황을 구분해 볼 수 있습니다. 외부 공개 조건에 직접 걸려 있는 유일한 내부 화면입니다.',
    value: ['장애를 사용자 문의보다 먼저 발견', '수집 실패 후 복구까지 걸린 시간', '조치 사유 기록 누락 0건'],
    elements: [
      { name: '권한 검사(요청마다 DB 역할 확인)', state: '구현', tone: 'live' },
      { name: '회원 요약·목록·상세', state: '구현', tone: 'live' },
      { name: '정지·해제·강제 로그아웃(사유 필수)', state: '구현', tone: 'live' },
      { name: '자기·타 관리자 조치 차단', state: '구현', tone: 'live' },
      { name: '조치 기록(account_admin_action)', state: '구현', tone: 'live' },
      { name: '큐 상태 읽기 API(4개 큐)', state: '구현', tone: 'live' },
      { name: '관리자 화면 큐 위젯', state: '미구현', tone: 'gap' },
      { name: 'DLQ 일괄 재생·자동 재시도', state: '미구현', tone: 'gap' },
      { name: 'CSV 내보내기', state: '미구현', tone: 'gap' },
    ],
    next: ['큐 상태를 화면 위젯으로 노출', 'DLQ 재생 도구 범위 결정'],
    questions: ['큐 모니터를 어드민에 넣을지, 별도 대시보드로 뺄지'],
    history: [
      { date: '2026-09-13', who: '김건우', what: '관리자 전용 큐 상태 읽기 API — 리포트 생성·발송·중복 검토·문서 분석의 DB 상태와 브로커 현황 구분', ref: 'main 통합' },
      { date: '2026-09-12', who: '이성민', what: '관리자 계정 관리 구현 — 요약·목록·상세와 정지·해제·강제 로그아웃, 조치 기록·자기 계정 차단', ref: 'V19 · main 통합' },
      { date: '2026-09-08', who: '김건우', what: '표 가로 스크롤 키보드 접근성, 미연결 버튼 비활성화', ref: 'UI-20' },
      { date: '2026-09-08', who: '이성민', what: '어드민 화면 최초 추가(예시 데이터)', ref: 'PR #89' },
    ],
  },

  // ── 시안만 ────────────────────────────────────────────
  {
    no: '16', key: 'compare', group: '시안만', name: '공고 비교', route: '미정', owner: '미배정',
    prio: 'P2', prioWhy: '착수 전 — 발표에서는 다음 계획으로 소개',
    tagline: '선택의 이유를 명확하게 — 시안에만 존재하는 화면', status: '시안만 · 미구현', tone: 'gap',
    demo: false, notes: [],
    lastChanged: '시안 기준',
    biz: '담당자는 보통 2~3개 공고를 놓고 고릅니다. 비교 화면은 "무엇을 신청할지"를 결정하는 마지막 관문이고, 지원금액·마감·요건 난이도를 나란히 놓으면 검색 품질이 조금 부족해도 사용자가 스스로 판단할 수 있습니다. 다만 중복 지원·수혜 검토가 "함께 신청 가능한가"를 먼저 다루기 시작해, 두 화면의 역할 구분이 필요합니다.',
    value: ['비교를 거친 뒤 상세·원문 질문으로 넘어가는 비율', '비교 담기 평균 2건 이상'],
    elements: [
      { name: '비교 담기(최대 N건)', state: '미구현', tone: 'gap' },
      { name: '항목별 나란히 표', state: '미구현', tone: 'gap' },
      { name: '차이 강조 표시', state: '미구현', tone: 'gap' },
      { name: '비교 상태 저장', state: '미구현', tone: 'gap' },
    ],
    next: ['중복 지원·수혜 검토와 역할 구분 확정', '비교 축(지원금액·마감·자격·서류) 확정'],
    questions: ['중복 검토 화면이 비교를 흡수할 수 있는가?', '비교는 검색 결과 안의 패널인가, 별도 화면인가?'],
    history: [
      { date: '2026-09-06', who: '팀원 시안', what: 'UI Explorer 시안에 공고 비교 화면으로 정의됨', ref: '외부 시안 · 착수 전' },
    ],
  },
];
